source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
xcodeproj 'RLGoogleDirectionsSample.xcodeproj'

pod 'Google-Maps-iOS-SDK'
pod 'RLGoogleDirections', :git => 'https://github.com/poulpix/RLGoogleDirections.git'

use_frameworks!
